### ISSUE TITLE
Support binary

### ISSUE THREAD

**Issue by dannysheridan** [fern-openai/open-ai-api#2]
The Fern Definition doesn't support binary today. Modeled as a string for now.

```
file: 
    description: |
      The audio file to transcribe, in one of these formats: mp3, mp4, mpeg, mpga, m4a, wav, or webm.
    type: string
    format: binary
```
