### ISSUE TITLE
Support for oneOf

### ISSUE THREAD

**Issue by dannysheridan** [fern-openai/open-ai-api#3]
We don't support oneOf today so I modeled as `optional<list<string>>`

```
stop:
    description: |
      Up to 4 sequences where the API will stop generating further tokens.
    default: null
    oneOf:
      - type: string
        nullable: true
      - type: array
        minItems: 1
        maxItems: 4
        items:
          type: string
```
